*****************************************************
*** Test file for the reader
***
*** J.L. Klaufus - Cranfield 1999
***

#Definition of geometry
$GEOMETRY

#Definition of surface 1
$SURFACE

#Definition of points
$POINTS
  3 3
#
  0.00 0.00 0.00
  0.00 0.00 0.00
  0.00 0.00 0.00
#
  0.00 5.00 10.00
  0.00 5.00 10.00
  0.00 5.00 10.00
#
  10.00 10.00 10.00
   5.00  5.00  5.00
   0.00  0.00  0.00
$END

$END

$END

