/********************************************************
*** Body file for definition of class clAc3dObject
***
*** J.L. Klaufus - Haarlem 2010
**/

#include <fstream>
#include <sstream>
#include <stdlib.h>
#include <string>

#include "ac3dobject.h"
#include "ac3dsurface.h"
#include "exceptiontree.h"
#include "globals.h"
#include "node3d.h"

using namespace std;

clAc3dObject::clAc3dObject(void)
{
  this->SetObjectType(otAc3dObject);
  this->SetObjectID(0);
}

clAc3dObject::clAc3dObject(const int ID, const string theName)
{
  this->SetObjectType(otAc3dObject);
  this->SetObjectID(ID);
  this->SetName(theName);
}

clAc3dObject::clAc3dObject(const clAc3dObject &source)
{
  try
  {
    Assign(source);
  }

  catch(clExceptionTree EX)
  {
    EX.AddMethodToTree("clAc3dObject::clAc3dObject");
    throw EX;
  }
}

clAc3dObject::~clAc3dObject(void)
{
  for(unsigned int v=0; v<GetNumberVertices(false); v++) delete GetVertexPointer(v);
  for(unsigned int s=0; s<GetNumberSurfaces(false); s++) delete GetSurfacePointer(s);
  for(unsigned int k=0; k<GetNumberKids(false); k++)     delete GetKidPointer(k);

  //cerr << "DESTROYING SURFACEGRID: " << GetNumberID() << endl;
}

unsigned int clAc3dObject::GetNumberVertices(bool aggregated = false) const
{
  unsigned int numberVertices = vertexList.size();

  if(aggregated)
  {
    for(unsigned int k=0; k<GetNumberKids(false); k++)
    {
      clAc3dObject *kidObject = GetKidPointer(k);
      numberVertices += kidObject->GetNumberVertices(aggregated);
    }
  }

  return (numberVertices);
}

unsigned int clAc3dObject::GetNumberSurfaces(bool aggregated = false) const
{
  unsigned int numberSurfaces = surfaceList.size();

  if(aggregated)
  {
    for(unsigned int k=0; k<GetNumberKids(false); k++)
    {
      clAc3dObject *kidObject = GetKidPointer(k);
      numberSurfaces += kidObject->GetNumberSurfaces(aggregated);
    }
  }

  return (numberSurfaces);
}

unsigned int clAc3dObject::GetNumberKids(bool aggregated = false) const
{
  unsigned int numberKids = kidList.size();

  if(aggregated)
  {
    for(unsigned int k=0; k<GetNumberKids(false); k++)
    {
      clAc3dObject *kidObject = GetKidPointer(k);
      numberKids += kidObject->GetNumberSurfaces(aggregated);
    }
  }

  return (numberKids);
}

void clAc3dObject::GetVertices(vector<clNode3D*> &vertexVector, bool aggregated = false) const
{
  try
  {
    for(unsigned int v=0; v<vertexList.size(); v++)
    {
      clNode3D* node3d = GetVertexPointer(v);
      vertexVector.push_back(node3d);
    }

    if(aggregated)
    {
      for(unsigned int k=0; k<GetNumberKids(false); k++)
      {
        clAc3dObject *kidObject = GetKidPointer(k);
        kidObject->GetVertices(vertexVector, aggregated);
      }
    }
  }

  catch(clExceptionTree EX)
  {
    EX.AddMethodToTree("clAc3dObject::GetVertices");
    throw EX;
  }
}

clAc3dObject& clAc3dObject::Assign(const clAc3dObject &source)
{
  try
  {

  }

  catch(clExceptionTree EX)
  {
    EX.AddMethodToTree("clAc3dObject::Assign");
    throw EX;
  }

  return(*this);
}

clAc3dObject& clAc3dObject::operator=(const clAc3dObject &source)
{
  return(Assign(source));
}

void clAc3dObject::WriteLegacyVTKFile(void)
{
  try
  {
    WriteLegacyVTKFile("ac3dObject.vtk");
  }

  catch(clExceptionTree EX)
  {
    EX.AddMethodToTree("clAc3dObject::WriteLegacyVTKGrid");
    throw EX;
  }
}

void clAc3dObject::WriteLegacyVTKFile(const string fileName)
{
  try
  {
    WriteLegacyVTKFile(fileName.c_str());
  }

  catch(clExceptionTree EX)
  {
    EX.AddMethodToTree("clAc3dObject::WriteLegacyVTKFile");
    throw EX;
  }
}

void clAc3dObject::WriteLegacyVTKFile(const char* fileName)
{
  try
  {
    fstream fout;
    fout.open(fileName, ios::out);
    fout.precision(3);
    if (fout.good())
    {
      // HEADER
      fout << "# vtk DataFile Version 2.0" << endl;

      // TITLE
      fout << "Grid generated by gridLab. FileName: " << fileName << "\n";

      // DATA TYPE
      fout << "ASCII" << endl;

      // DATASET
      fout << "DATASET POLYDATA" << endl;

      // POINTS
      fout << "POINTS " << this->GetNumberVertices(true) << " double" << endl;
      WriteVTKPoints(fout, *this);
      fout << endl;

      // POLYGONS
      stringstream tempStream;
      unsigned int totalNumberVertices = 0;
      unsigned int cellListSize = WriteVTKPolygons(tempStream, *this, totalNumberVertices); // Write to temporary buffer, as to first to determine the cell list size
      fout << "POLYGONS " << this->GetNumberSurfaces(true) << " " << cellListSize << endl;
      fout << tempStream.rdbuf(); // Dump temporary bugger to file
      fout << endl;

      fout.close();
    }
    else
    {
      throw clExceptionTree("clAc3dObject", "WriteLegacyVTKFile", "Could not open output file.");
    }
  }

  catch(clExceptionTree EX)
  {
    EX.AddMethodToTree("clAc3dObject::WriteLegacyVTKGrid");
    throw EX;
  }
}

void clAc3dObject::WriteVTKPoints(iostream &fout, clAc3dObject &ac3dObject)
{
  try
  {
    for(unsigned int n=0; n<ac3dObject.GetNumberVertices(); n++)
    {
      clNode3D *node = ac3dObject.GetVertexPointer(n);
      tpMatrix<double> coordinates = node->GetCoordinates();

      fout << coordinates(1,1);
      for(int r=2; r<=coordinates.GetNumberRows(); r++)
      {
        fout << " " << coordinates(r, 1);
      }
      fout << endl;
    }

    for(unsigned int k=0; k<ac3dObject.GetNumberKids(); k++)
    {
      clAc3dObject *kidObject = ac3dObject.GetKidPointer(k);
      WriteVTKPoints(fout, *kidObject);
    }
  }

  catch(clExceptionTree EX)
  {
    EX.AddMethodToTree("clAc3dObject::WriteVTKPoints");
    throw EX;
  }
}

unsigned int clAc3dObject::WriteVTKPolygons(iostream &fout, clAc3dObject &ac3dObject, unsigned int &totalNumberVertices)
{
  int cellListSize = 0;

  try
  {
    for(unsigned int s=0; s<ac3dObject.GetNumberSurfaces(); s++)
    {
      clAc3dSurface *ac3dSurface = ac3dObject.GetSurfacePointer(s);

      unsigned int numberVertices = ac3dSurface->GetNumberVertices();
      cellListSize = cellListSize + 1 + numberVertices;

      fout << numberVertices;
      for(unsigned int v=0; v<numberVertices; v++)
      {
        fout << " " << (totalNumberVertices+ac3dSurface->GetVertexIndex(v));
      }
      fout << endl;
    }

    totalNumberVertices += ac3dObject.GetNumberVertices(false);
    for(unsigned int k=0; k<ac3dObject.GetNumberKids(); k++)
    {
      clAc3dObject *kidObject = ac3dObject.GetKidPointer(k);
      cellListSize += WriteVTKPolygons(fout, *kidObject, totalNumberVertices);
    }
  }

  catch(clExceptionTree EX)
  {
    EX.AddMethodToTree("clAc3dObject::WriteVTKPolygons");
    throw EX;
  }

  return (cellListSize);
}

void clAc3dObject::ReadAC3DFile(const string fileName)
{
  try
  {
    ReadAC3DFile(fileName.c_str());
  }

  catch(clExceptionTree EX)
  {
    EX.AddMethodToTree("clAc3dObject::ReadAC3DFile");
    throw EX;
  }
}

void clAc3dObject::ReadAC3DFile(const char* fileName)
{
  try
  {
    fstream file;
    file.open(fileName, ios::in);
    file.precision(3);
    if (file.good())
    {
      ParseAC3DFile(file);

      file.close();
    }
    else
    {
      throw clExceptionTree("clAc3dObject", "ReadAC3DFile", "Could not open input file.");
    }
  }

  catch(clExceptionTree EX)
  {
    EX.AddMethodToTree("clAc3dObject::ReadAC3DFile");
    throw EX;
  }
}

void clAc3dObject::ParseAC3DFile(fstream &file)
{
  try
  {
    // Read HEADER
    char header[5];
    file.get(header, 5);

    cout << "HEADER: " << header << endl;

    int version;
    file >> std::hex >> version;

    cout << "VERSION: " << version << endl;

    //TODO: Something with version number

    while(!file.eof())
    {
      ParseAC3DKid(file, *this);
    }
  }

  catch(clExceptionTree EX)
  {
    EX.AddMethodToTree("clAc3dObject::ParseAC3DFile");
    throw EX;
  }
}

void clAc3dObject::ParseAC3DKid(fstream &file, clAc3dObject &ac3dObject)
{
  try
  {
    string identifier;
    file >> identifier;

    if(identifier == "MATERIAL")
    {
      // TODO: Add material to object
      string line;
      getline(file, line);
    }
    else if(identifier == "OBJECT")
    {
      clAc3dObject *childAc3dObject = new clAc3dObject();
      ParseAC3DObject(file, *childAc3dObject);
      kidList.push_back(childAc3dObject);
    }
//    else
//    {
//      string message = "Unknown indentifier: ";
//      message += identifier;
//      throw clExceptionTree("clAc3dObject", "ParseAC3DKid", message);
//    }
  }

  catch(clExceptionTree EX)
  {
    EX.AddMethodToTree("clAc3dObject::ParseAC3DKid");
    throw EX;
  }
}

void clAc3dObject::ParseAC3DObject(fstream &file, clAc3dObject &ac3dObject)
{
  try
  {
    string type;
    file >> type;

    string identifier;
    file >> identifier;
    while(identifier != "kids")
    {
      if(identifier == "name")
      {
        string name;
        getline(file, name);
//        file >> name;

        cout << "Parsing OBJECT: " << name << "..." << endl;
        ac3dObject.SetName(name);
      }
      else if (identifier == "data")
      {
        // TODO: data
        string line;
        getline(file, line);
        getline(file, line);
      }
      else if (identifier == "texture")
      {
        // TODO: texture
        string line;
        getline(file, line);
      }
      else if (identifier == "texrep")
      {
        // TODO: texture repeats
        string line;
        getline(file, line);
      }
      else if (identifier == "crease")
      {
        // TODO: crease
        string line;
        getline(file, line);
      }
      else if (identifier == "rot")
      {
        // TODO: rotation matrix
        string line;
        getline(file, line);
      }
      else if (identifier == "loc")
      {
        // TODO: location offset
        string line;
        getline(file, line);
      }
      else if (identifier == "url")
      {
        // TODO: url
        string line;
        getline(file, line);
      }
      else if (identifier == "numvert")
      {
        string line;
        file >> line;

        long numberVertices = atoi(line.c_str());

//        cout << "NUMBER VERTICES: " << numberVertices << endl;

        for(int v=0; v<numberVertices; v++)
        {
          double x, y, z;
          file >> x >> y >> z;

//          cout << x << " " << y << " " << z << endl;

          clNode3D *vertex = new clNode3D();
          vertex->SetCoordinates(x, y, z);
          ac3dObject.AddVertex(vertex);
        }
      }
      else if (identifier == "numsurf")
      {
        string line;
        file >> line;

        int numberSurfaces = atoi(line.c_str());
//        cout << "NUMBER SURFACES: " << numberSurfaces << endl;

        for(int s=0; s<numberSurfaces; s++)
        {
          clAc3dSurface *ac3dSurface = new clAc3dSurface();
          ParseAC3DSurface(file, *ac3dSurface);
          ac3dObject.AddSurface(ac3dSurface);
        }
      }
      else
      {
        string message = "Unknown indentifier: ";
        message += identifier;
        throw clExceptionTree("clAc3dObject", "ParseAC3DObject", message);
      }

      file >> identifier;
    }

    string line;
    file >> line;

    int numberKids = atoi(line.c_str());

//    cout << "NUMBERKIDS: " << numberKids << endl;

    for(int k=0; k<numberKids; k++)
    {
      ParseAC3DKid(file, ac3dObject);
    }
  }

  catch(clExceptionTree EX)
  {
    EX.AddMethodToTree("clAc3dObject::ParseAC3DObject");
    throw EX;
  }
}

void clAc3dObject::ParseAC3DSurface(fstream &file, clAc3dSurface &ac3dSurface)
{
  try
  {
    string identifier;
    file >> identifier;

    if(identifier != "SURF")
    {
      string message = "Expected surface, but got: ";
      message += identifier;
      throw clExceptionTree("clAc3dObject", "ParseAC3DSurface", message);
    }

    int flags;
    file >> std::hex >> flags;
    // TODO: Do something with flags

    file >> identifier;
    while(identifier != "refs")
    {
      if(identifier == "mat")
      {
        // TODO: material index
        string line;
        getline(file, line);
      }
      else
      {
        throw clExceptionTree("clAc3dObject", "ParseAC3DSurface", "Unknown indentifier.");
      }

      file >> identifier;
    }

    string line;
    getline(file, line);

    int numberReferences = atoi(line.c_str());
//    cout << "NUMBER REFERENCES: " << numberReferences << endl;

    for(int r=0; r<numberReferences; r++)
    {
      string line;
      file >> line;

      int vertexIndex = atoi(line.c_str());
      ac3dSurface.AddVertexIndex(vertexIndex);

      getline(file, line); // Skip remainder of line
    }
  }

  catch(clExceptionTree EX)
  {
    EX.AddMethodToTree("clAc3dObject::ParseAC3DObject");
    throw EX;
  }
}

